#!/usr/bin/env python3
"""Matched-radius audit for the verifier-gated SafeMPPI proposal controller.

This diagnostic deliberately keeps native SafeMPPI and the clean runtime
backup semantics separate.  The native expert is generated by
``giant_obstacle_ood/stage1b_smooth_expert.py``.  Here each cost-selected H=10
SafeMPPI proposal is submitted to the unchanged full verifier before its first
action can execute.  Raw debug candidates are audit-only, exactly as in the
planned-demo contract.

Changing ``--radii`` changes geometry only.  No demonstration replay, LwF,
anchoring, negative objective, or success-conditioned data injection occurs.
"""
from __future__ import annotations

import argparse
from dataclasses import asdict
from datetime import datetime, timezone
import json
import math
from pathlib import Path
import time
from typing import Any, Sequence

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import numpy as np
import torch

from .config import GAMMAS, clean_method_absence_manifest
from .evaluation import detour_mode
from .scene import GOAL, START, make_ood_scene
from .stage2_planned_demos import DemoRunConfig, run_expert_rollout


DEFAULT_OUTDIR = (
    Path(__file__).resolve().parent
    / "stage_results/faithful_radius_restart_20260716/01_certified_expert_sweep"
)


def _clearance(path: np.ndarray, env: Any) -> np.ndarray:
    obstacles = env.obstacles.detach().cpu().numpy().astype(np.float64, copy=False)
    return (
        np.linalg.norm(path[:, None] - obstacles[None, :, :2], axis=2)
        - obstacles[None, :, 2]
        - float(env.r_robot)
    ).min(axis=1)


def _row(episode: dict[str, Any], env: Any, radius: float, attempt: int) -> dict[str, Any]:
    path = np.asarray(episode["path"], dtype=np.float64)
    clearance = _clearance(path, env)
    return {
        "radius": float(radius),
        "gamma": float(episode["gamma"]),
        "attempt": int(attempt),
        "seed": int(episode["seed"]),
        "success": bool(episode["success"]),
        "collision": bool(episode["collision"]),
        "in_bounds": bool(episode["in_bounds"]),
        "failure_reason": episode["dead_reason"],
        "steps": int(episode["steps"]),
        "time_s": float(episode["steps"] * float(env.dt)),
        "endpoint_distance_m": float(episode["endpoint_distance_m"]),
        "min_clearance_m": float(clearance.min(initial=np.inf)),
        "mean_clearance_m": float(clearance.mean()),
        "path_length_m": float(episode["path_length_m"]),
        "detour_mode": detour_mode(path),
        "query_count": int(episode["queries"]),
        "safe_query_count": int(episode["safe_queries"]),
        "query_acceptance": float(episode["query_acceptance"]),
        "selected_plan_kinds": [
            str(episode["query_kinds"][index])
            for index in np.asarray(episode["selected_query_indices"], dtype=int)
        ],
        "path": path.astype(np.float32),
    }


def _summary(rows: Sequence[dict[str, Any]], radius: float) -> dict[str, Any]:
    group = [row for row in rows if math.isclose(row["radius"], radius)]
    successful = [row for row in group if row["success"]]
    modes = sorted({row["detour_mode"] for row in successful})
    reasons: dict[str, int] = {}
    for row in group:
        key = "success" if row["success"] else str(row["failure_reason"])
        reasons[key] = reasons.get(key, 0) + 1
    return {
        "radius": float(radius),
        "attempts": len(group),
        "successes": len(successful),
        "success_rate": len(successful) / max(len(group), 1),
        "collisions": sum(row["collision"] for row in group),
        "timeouts": sum(row["failure_reason"] == "timeout" for row in group),
        "fail_closed": sum(
            row["failure_reason"] in {
                "no_certified_plan", "no_certified_cost_selected_plan"
            }
            for row in group
        ),
        "mean_query_acceptance": float(np.mean([row["query_acceptance"] for row in group])),
        "mean_success_time_s": (
            float(np.mean([row["time_s"] for row in successful])) if successful else None
        ),
        "mean_success_clearance_m": (
            float(np.mean([row["mean_clearance_m"] for row in successful]))
            if successful else None
        ),
        "minimum_success_clearance_m": (
            float(min(row["min_clearance_m"] for row in successful))
            if successful else None
        ),
        "successful_detour_modes": modes,
        "outcomes": reasons,
    }


def _render(rows: Sequence[dict[str, Any]], radii: Sequence[float], output: Path) -> None:
    fig, axes = plt.subplots(1, len(radii), figsize=(5.0 * len(radii), 4.8), squeeze=False)
    gamma_colors = dict(zip(GAMMAS, plt.cm.plasma(np.linspace(0.08, 0.92, len(GAMMAS)))))
    for axis, radius in zip(axes.ravel(), radii):
        env = make_ood_scene(radius=float(radius))
        for obstacle in env.obstacles.detach().cpu().numpy():
            axis.add_patch(Circle(obstacle[:2], obstacle[2], color="0.65", ec="none"))
        for row in rows:
            if not math.isclose(row["radius"], float(radius)):
                continue
            path = row["path"]
            axis.plot(path[:, 0], path[:, 1], color=gamma_colors[row["gamma"]], lw=1.1, alpha=0.8)
            if not row["success"]:
                axis.plot(path[-1, 0], path[-1, 1], "x", color="#cc3311", ms=6)
        summary = _summary(rows, float(radius))
        axis.plot(START[0], START[1], "ks", ms=5)
        axis.plot(GOAL[0], GOAL[1], "*", color="#ffcc00", mec="black", ms=10)
        axis.set(
            xlim=(-0.15, 5.15), ylim=(-0.15, 5.15), aspect="equal",
            title=(f"radius {radius:.2f}: SR {summary['successes']}/{summary['attempts']}\n"
                   f"timeout {summary['timeouts']}, fail-closed {summary['fail_closed']}, "
                   f"collision {summary['collisions']}")
        )
    fig.suptitle("Verifier-gated SafeMPPI proposal controller — matched geometry-only sweep")
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=180, facecolor="white")
    plt.close(fig)


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--radii", type=float, nargs="+", default=(1.20, 1.15, 1.10))
    parser.add_argument("--attempts-per-gamma", type=int, default=2)
    parser.add_argument("--seed0", type=int, default=65_100)
    parser.add_argument("--max-steps", type=int, default=800)
    parser.add_argument("--reach", type=float, default=0.15)
    parser.add_argument("--smooth-weight", type=float, default=8.0)
    parser.add_argument("--noise-var-mult", type=float, default=3.0)
    parser.add_argument("--retreat-weight", type=float, default=0.0)
    parser.add_argument("--max-debug-candidates", type=int, default=6)
    parser.add_argument("--max-proposals", type=int, default=8)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    args = parser.parse_args(argv)
    if args.attempts_per_gamma <= 0 or args.max_steps <= 0:
        raise ValueError("attempt and step budgets must be positive")
    if len(set(float(radius) for radius in args.radii)) != len(args.radii):
        raise ValueError("--radii must be unique")

    device = torch.device(args.device)
    if device.type == "cuda":
        torch.cuda.set_device(device)
    config = DemoRunConfig(
        max_steps=args.max_steps,
        reach_m=args.reach,
        smooth_weight=args.smooth_weight,
        retreat_weight=args.retreat_weight,
        noise_var_mult=args.noise_var_mult,
        max_debug_candidates=args.max_debug_candidates,
        max_proposals_per_step=args.max_proposals,
        quota_per_direction=1,
        max_candidate_seeds_per_gamma=args.attempts_per_gamma,
        seed0=args.seed0,
    )
    rows: list[dict[str, Any]] = []
    started = time.perf_counter()
    for radius in args.radii:
        env = make_ood_scene(radius=float(radius))
        env.T = int(args.max_steps)
        for gamma in GAMMAS:
            for attempt in range(args.attempts_per_gamma):
                seed = int(args.seed0 + attempt)
                episode = run_expert_rollout(
                    env=env, gamma=float(gamma), seed=seed, device=device, config=config,
                )
                row = _row(episode, env, float(radius), attempt)
                rows.append(row)
                print(
                    f"radius={radius:.2f} gamma={gamma:g} seed={seed} "
                    f"status={'success' if row['success'] else row['failure_reason']} "
                    f"steps={row['steps']} accept={row['query_acceptance']:.3f}",
                    flush=True,
                )

    serial_rows = [{key: value for key, value in row.items() if key != "path"} for row in rows]
    payload = {
        "schema": "afe_verifier_gated_expert_radius_sweep_v1",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "wall_seconds": time.perf_counter() - started,
        "radii": [float(radius) for radius in args.radii],
        "gammas": list(GAMMAS),
        "config": asdict(config),
        "semantics": {
            "controller": "SafeMPPI cost-selected mean/best proposals, then full verifier",
            "debug_candidates": "fully audited but never executed",
            "selection": "best progress among fully verified-safe cost-selected plans",
            "no_safe_plan": "fail closed without state transition",
            "native_expert_reported_separately": True,
        },
        "prohibited_mechanisms": clean_method_absence_manifest(),
        "summaries": [_summary(rows, float(radius)) for radius in args.radii],
        "rows": serial_rows,
    }
    args.outdir.mkdir(parents=True, exist_ok=True)
    (args.outdir / "logs").mkdir(exist_ok=True)
    (args.outdir / "data").mkdir(exist_ok=True)
    (args.outdir / "viz").mkdir(exist_ok=True)
    (args.outdir / "logs/summary.json").write_text(json.dumps(payload, indent=2) + "\n")
    np.savez_compressed(
        args.outdir / "data/paths.npz",
        radii=np.asarray([row["radius"] for row in rows]),
        gammas=np.asarray([row["gamma"] for row in rows]),
        seeds=np.asarray([row["seed"] for row in rows]),
        success=np.asarray([row["success"] for row in rows]),
        paths=np.asarray([row["path"] for row in rows], dtype=object),
    )
    _render(rows, args.radii, args.outdir / "viz/radius_sweep.png")
    print(json.dumps(payload["summaries"], indent=2), flush=True)


if __name__ == "__main__":
    main()
